name: docker-login-workflow-called

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:

      # - name: get properties
      #   id: json_properties
      #   run: |
      #     echo "RELEASE_TAG=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      # - run: |
      #     echo "Build tag==> ${{ steps.json_properties.outputs.RELEASE_TAG }}"

      - name: start docker login
        run: |
          docker login -u ${{ secrets.MY_DOCKER_USERNAME }} -p ${{ secrets.MY_DOCKER_PASSWORD }}

      # ## Build dockerfile ##
      # - name: Build the Docker image
      #   run: |
      #     docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:${{ steps.json_properties.outputs.RELEASE_TAG }}