name: POC_append_file
on: 
  workflow_dispatch:
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/append-file.yaml
jobs:
  append-file:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
            echo "today=$(TZ='Asia/Bangkok' date +'%Y%m%d-%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: create new file
        run: |
            touch build_info.txt

            echo "Repo Name: ${{ github.repository.name }}
            Version: 0.0.1
            Pipeline Count Number: ${{ github.run_number }}
            Build Date Time: ${{steps.date.outputs.today}}
            Git Commit Hash: ${{ github.sha }}" >> build_info.txt

            cat build_info.txt
            

