name: Auth User
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/authorized-user.yaml
jobs:
  auth_by_username:
    if: github.actor == 'pongsathorn-92432' 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production"
    
      - name: Create/Update environment
        run: |
            gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/ais-pci-spdg/mpay-modernization-devops/environments/uat \
            -F "wait_timer=30" -F "prevent_self_review=false" -f "reviewers[][type]=User" \
            -F "reviewers[][id]=1" -f "reviewers[][type]=Team" -F "reviewers[][id]=1" \
            -F "deployment_branch_policy[protected_branches]=false" -F "deployment_branch_policy[custom_branch_policies]=true"


