name: Authen wtih managed identity
on: 
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: "73b06f9f-a9c0-4458-90bf-f128b18f6149" ##${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: "23f8cd51-9a3f-4441-a772-73d6eaf31061" ##${{ secrets.AZURE_TENANT_ID }}
          subscription-id: "756952db-9653-4f48-bed7-49ea8d2a8ada" ##${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: az cli
        run: |
          az resource list
