name: POC_checkout
on: 
  push:
    branches: 
      - action-ci
      - 'feature/**'
    paths:
      - .github/workflows/ckout-branch.yaml

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: |
          git branch -a
          ls -R

