name: POC_checkout_feature
on: 
  push:
    branches: 
      - 'feature/**'

jobs:
  checkout_feature:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: |
          git branch -a
          ls -R
          echo "Branch Name: ${GITHUB_REF}"

