name: POC_checkout
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/ckout-branch.yaml

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
            repository: brightza008/poc-helmchart
      - run: |
          ls -R
          echo "Start Helm!!"
          helm version
