name: POC-reuse-workflow
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

env: 
    docker_user: ${{vars.MY_DOCKER_USERNAME}}
    docker_password: ${{secrets.MY_DOCKER_PASSWORD}}

    AZ_CONTAINER_REGISTRY: bbbacr.azurecr.io
    AZ_CONTAINER_NAME: bbbacr

    HELM_TEMPLATE_REPO: brightza008/poc-helmchart
    HELM_TEMPLATE_BRANCH: minikube

jobs:
  env_workflow:
    runs-on: ubuntu-latest
    name: Setup Output Env
    outputs: 
      user: ${{env.docker_user}}
      pass: ${{env.docker_password}}

      AZ_CONTAINER_REGISTRY: ${{env.AZ_CONTAINER_REGISTRY}}
      AZ_CONTAINER_NAME: ${{env.AZ_CONTAINER_NAME}}
      HELM_TEMPLATE_REPO: ${{env.HELM_TEMPLATE_REPO}}
      HELM_TEMPLATE_BRANCH: ${{env.HELM_TEMPLATE_BRANCH}}
    steps:
      - run: |
          echo "preparing output env"

  Build_Docker:
    needs: env_workflow
    if: contains(github.event.commits[0].message, 'hub')
    name: "Build Docker to dockerhub"
    uses: brightza008/poc-github-workflow/.github/workflows/docker-build.yaml@workflow
    with:
      username: ${{ needs.env_workflow.outputs.user }}
      # username: ${{vars.MY_DOCKER_USERNAME}}
    secrets:
      # token: ${{ needs.env_workflow.outputs.pass }}
      token: ${{secrets.MY_DOCKER_PASSWORD}}

  Setup_AZ_Reources:
    if: contains(github.event.commits[0].message, 'login')
    name: "Calling workflow Azure login"
    uses: brightza008/poc-github-workflow/.github/workflows/az-authen.yaml@workflow
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}


  Build_Docker_ACR:
    needs: env_workflow
    if: contains(github.event.commits[0].message, 'az')
    name: "Build Docker to ACR"
    uses: brightza008/poc-github-workflow/.github/workflows/docker-build-acr.yaml@workflow
    with:
      AZ_CONTAINER_REGISTRY: ${{needs.env_workflow.outputs.AZ_CONTAINER_REGISTRY}}
      AZ_CONTAINER_NAME: ${{needs.env_workflow.outputs.AZ_CONTAINER_NAME}}
    secrets: inherit #PASS ALL SECRETS TO REUSE-WORKFLOW
      # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  Deploy_helm:
    needs: [env_workflow] 
    if: contains(github.event.commits[0].message, 'de')
    name: "Helm deploy to AKS"
    uses: brightza008/poc-github-workflow/.github/workflows/helm-aks.yaml@workflow
    with:
      HELM_TEMPLATE_REPO: ${{needs.env_workflow.outputs.HELM_TEMPLATE_REPO}}
      HELM_TEMPLATE_BRANCH: ${{needs.env_workflow.outputs.HELM_TEMPLATE_BRANCH}}
      AZ_RESOURCE_GROUP: brightza008-rg
      AZ_AKS_NAME: brightza008-aks
    secrets: inherit 
