name: POC-reuse-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml
jobs:
  call-workflow-A:
    uses: ./.github/workflows/docker-build.yaml@workflow
    with: 
      username: ${{ secrets.MY_DOCKER_USERNAME }}
      #token: ${{ secrets.MY_DOCKER_PASSWORD }}
 
