name: POC-reuse-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
jobs:
  call-workflow-A:
    uses: brightza008/poc-github-action/.github/workflows/main-nodejs.yaml@workflow
 
