name: POC-reuse-workflow
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

env: 
    docker_user: ${{vars.MY_DOCKER_USERNAME}}
    docker_password: ${{secrets.MY_DOCKER_PASSWORD}}

    AZ_CONTAINER_REGISTRY: bbbacr.azurecr.io
    AZ_CONTAINER_NAME: bbbacr
  

jobs:
  env_workflow:
    runs-on: ubuntu-latest
    name: Setup Output Env
    outputs: 
      user: ${{env.docker_user}}
      pass: ${{env.docker_password}}
    steps:
      - run: |
          echo "preparing output env"

  Build_Docker:
    needs: env_workflow
    if: contains(github.event.commits[0].message, 'hub')
    name: "Build Docker to dockerhub"
    uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
    with:
      username: ${{ needs.env_workflow.outputs.user }}
      # username: ${{vars.MY_DOCKER_USERNAME}}
    secrets:
      # token: ${{ needs.env_workflow.outputs.pass }}
      token: ${{secrets.MY_DOCKER_PASSWORD}}

  Setup_AZ_Reources:
    if: contains(github.event.commits[0].message, 'login')
    name: "Azure login"
    uses: brightza008/poc-github-action/.github/workflows/az-authen.yaml@workflow



  Build_Docker_ACR:
    if: contains(github.event.commits[0].message, 'az')
    name: "Build Docker to ACR"
    uses: brightza008/poc-github-action/.github/workflows/docker-build-acr.yaml@workflow
 
  setup-up-azure-resources:
    if: contains(github.event.commits[0].message, 'az')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: get properties
        id: json_properties
        run: |
          echo "RELEASE_TAG=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - run: |
          echo "Build tag==> ${{ steps.json_properties.outputs.RELEASE_TAG }}"

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: start docker login
        run: |
          az acr login -n ${{env.AZ_CONTAINER_NAME}}

      ## Build dockerfile ##
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:${{ steps.json_properties.outputs.RELEASE_TAG }}
          docker tag ${{ github.event.repository.name }}:${{ steps.json_properties.outputs.RELEASE_TAG }} ${{env.AZ_CONTAINER_REGISTRY}}/${{ github.event.repository.name }}:${{ steps.json_properties.outputs.RELEASE_TAG }}
          docker push ${{env.AZ_CONTAINER_REGISTRY}}/${{ github.event.repository.name }}:${{ steps.json_properties.outputs.RELEASE_TAG }}
 
