name: POC-reuse-workflow
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

env: 
    docker_user: ${{vars.MY_DOCKER_USERNAME}}
    docker_password: ${{secrets.MY_DOCKER_PASSWORD}}

jobs:
  env_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    name: Setup Output Env
    outputs: 
      user: ${{env.docker_user}}
      pass: ${{env.docker_password}}
    steps: 
      - run: |
          echo "preparing output env"
    
  Build_Docker:
    needs: env_workflow
    name: "Build Docker"
    uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
    with:
      # username: ${{ needs.env_workflow.outputs.user }}
      username: ${{vars.MY_DOCKER_USERNAME}}
    secrets:
      # token: ${{ needs.env_workflow.outputs.pass }}
      token: ${{secrets.MY_DOCKER_PASSWORD}}

