name: POC-reuse-workflow
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

env: 
    docker_user: ${{vars.MY_DOCKER_USERNAME}}
    docker_password: ${{secrets.MY_DOCKER_PASSWORD}}

jobs:
  env_workflow:
    runs-on: ubuntu-latest
    name: Setup Output Env
    outputs: 
      user: ${{env.docker_user}}
      pass: ${{env.docker_password}}
    steps:
      - run: |
          echo "preparing output env"

  Build_Docker:
    needs: env_workflow
    name: "Build Docker"
    uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
    with:
      # username: ${{ needs.env_workflow.outputs.user }}
      username: ${{vars.MY_DOCKER_USERNAME}}
    secrets:
      # token: ${{ needs.env_workflow.outputs.pass }}
      token: ${{secrets.MY_DOCKER_PASSWORD}}

  Setup_AZ_Reources:
    if: contains(github.event.commits[0].message, 'az')
    name: "Azure login"
    uses: brightza008/poc-github-action/.github/workflows/az-authen.yaml@workflow
  Build_Docker_ACR:
    if: contains(github.event.commits[0].message, 'az')
    name: "Build Docker to ACR"
    uses: brightza008/poc-github-action/.github/workflows/docker-build-acr.yaml@workflow
 