name: POC-reuse-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

env:
  dockerhub_username: ${{ vars.MY_DOCKER_USERNAME }}

jobs:
  call-workflow-A:
    uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
    with:
      username: ${{vars.MY_DOCKER_USERNAME}}
    secrets:
      token: ${{ secrets.MY_DOCKER_PASSWORD }}

  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: |
        echo "echo from Gibhub variable: ${dockerhub_username}"

    # with: 
    #   username: ${{ secrets.MY_DOCKER_USERNAME }}
    #   token: ${{ secrets.MY_DOCKER_PASSWORD }}
 
