name: POC-reuse-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yaml

# # env:
# #   var1: hello_var1
# #   # dockerhub_username: ${{ vars.MY_DOCKER_USERNAME }}

# jobs:
#   call-workflow-A:
#     runs-on: ubuntu-latest
#     env:
#         dockerhub_username: 'user1'
#   steps:
#     uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
#     with:
#       username: ${{ env.dockerhub_username }}
#     secrets:
#       token: ${{ secrets.MY_DOCKER_PASSWORD }}

#   echo:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Build the Docker image
#       run: |
#         echo "echo from Github variable: ${dockerhub_username}"

################
# jobs:
#   build:
#     env:
#         JAVA_VERSION: '11'
#   steps:
#   - uses: actions/checkout@v3
#   - name: Set up JDK ${{env.JAVA_VERSION}}
#   uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
#   with:
#     username: ${{ env.dockerhub_username }}
#   secrets:
#     token: ${{ secrets.MY_DOCKER_PASSWORD }}


jobs:
  build:
    env:
        docker_username: ${{vars.MY_DOCKER_USERNAME}}

    runs-on: ubuntu-latest

    steps:
    - uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
      with:
        username: ${{ env.dockerhub_username }}
        secrets:
        token: ${{ secrets.MY_DOCKER_PASSWORD }}
