name: Node.js CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
jobs:
  call-workflow-A:
    uses: ./.github/workflows/pipeline-orchestrator/archetypes/nodejs/main-nodejs.yaml@action-ci
