name: POC-reuse-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/demo-workflow-caller.yml
jobs:
  call-workflow-A:
    uses: brightza008/poc-github-action/.github/workflows/docker-build.yaml@workflow
    with: 
      username: ${{ secrets.MY_DOCKER_USERNAME }}
    secrets: 
        token: ${{ secrets.MY_DOCKER_PASSWORD }}
 
