name: Related Dropdowns Example

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: "Service Type"
        required: true
        type: choice
        options:
          - java
          - WebhostingBuildAndZip
          - WebhostingZipOnly
      webtarget:
        description: "Target Web(related to runtime Webhosting)"
        required: true
        default: "Default"
        type: choice
        options:
          - none
          - WEBHOSTING001
          - WEBHOSTING002
          - WEBHOSTING003

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Input Relationship
        run: |
          echo "Runtime: ${{ github.event.inputs.runtime }}"
          echo "Web Target: ${{ github.event.inputs.webtarget }}"
          case ${{ github.event.inputs.runtime }} in
            "WebhostingBuildAndZip")
              case ${{ github.event.inputs.webtarget }} in
                "WEBHOSTING001"|"WEBHOSTING003")
                  echo "Runtime=${{ github.event.inputs.runtime }}  with -> ${{ github.event.inputs.webtarget }}"
                  ;;
                *)
                  echo "\033[1;31m*** Invalid Runtime or WebTarget // Please Check ..  ***\033[0m" >&2
                  exit 1
                  ;;
              esac
              ;;
            "WebhostingZipOnly")
              case ${{ github.event.inputs.webtarget }} in
                "WEBHOSTING002")
                  echo "Runtime=${{ github.event.inputs.runtime }}  with -> ${{ github.event.inputs.webtarget }}"
                  ;;
                *)
                  echo "\033[1;31m*** Invalid Runtime or WebTarget // Please Check ..  ***\033[0m" >&2
                  exit 1
                  ;;
              esac
              ;;
            *)
              echo "Invalid webtarget option!" >&2
              exit 1
              ;;
          esac
