name: POC Related Dropdowns
run-name: ${{ github.workflow }} - ${{ format('{0}', tojson(inputs)) || '' }}


on:
  workflow_dispatch:
    inputs:
      runtime:
        description: "Service Type"
        required: true
        type: choice
        options:
          - java
          - webhostingBuildAndZip
          - webhostingZipOnly
      webtarget:
        description: "Web Target (related to runtime Webhosting)"
        required: true
        default: "Default"
        type: choice
        options:
          - none
          - WEBHOSTING001
          - WEBHOSTING002
          - WEBHOSTING003

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Input Relationship
        if: ${{ inputs.webtarget != 'none' || startsWith(inputs.runtime, 'webhosting') }}
        run: |
          echo "Runtime: ${{ github.event.inputs.runtime }}"
          echo "WebTarget: ${{ github.event.inputs.webtarget }}"
          case ${{ github.event.inputs.runtime }} in
            "webhostingBuildAndZip")
              case ${{ github.event.inputs.webtarget }} in
                "WEBHOSTING001"|"WEBHOSTING003")
                  echo "Runtime=${{ github.event.inputs.runtime }}  with -> ${{ github.event.inputs.webtarget }}"
                  ;;
                *)
                  echo "\033[1;31m*** Invalid Runtime or WebTarget // Please Check ..  ***\033[0m" >&2
                  exit 1
                  ;;
              esac
              ;;
            "webhostingZipOnly")
              case ${{ github.event.inputs.webtarget }} in
                "WEBHOSTING002")
                  echo "Runtime=${{ github.event.inputs.runtime }}  with -> ${{ github.event.inputs.webtarget }}"
                  ;;
                *)
                  echo "\033[1;31m*** Invalid Runtime or WebTarget // Please Check ..  ***\033[0m" >&2
                  exit 1
                  ;;
              esac
              ;;
            *)
              echo "webtarget cannot be 'none'" >&2
              exit 1
              ;;
          esac

      - name: skipped validate
        run: |
            echo "g next"