name: Mixed inputs
on:
  workflow_dispatch:
    inputs:
      approval: 
        type: string
        default: approve
        required: true
      name:
        type: choice
        description: Who to greet
        options: 
        - bboy
        - ggirl
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

    - name: Check approval status
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          if [[ "${{ github.event.inputs.approval }}" == "approve" ]]; then
            echo "Workflow approved, continue with CI processes."
          else
            echo "Workflow not approved, stopping CI processes."
            exit 1
          fi
        fi
        
