# name: My Workflow

# on:
#   push:
#     branches:
#       - action-ci

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       {{ include('pipeline-orchestrator/archetypes/nodejs/main-nodejs.yaml') }}
#     # Paste the content of the main.yaml file here

#       - name: Another Step
#         run: echo "This is another step"


name: Main Workflow

on:
  push:
    branches:
      - action-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # {{ include('pipeline-orchestrator/modules/modules.yaml') }}
      - name: Import Modules
        run: |
          echo "modules=$(cat pipeline-orchestrator/modules/modules.yaml) >> $GITHUB_OUTPUT"
          # echo "::set-output name=modules2::$(cat modules2.yaml)"
          
      - name: Run Imported Modules
        run: |
          echo "${{ steps.import_modules.outputs.modules }}" > imported_modules.yaml
          # echo "${{ steps.import_modules.outputs.modules2 }}" >> imported_modules.yaml
          echo "::add-matcher::imported_modules.yaml"
          
      - name: Execute Job
        uses: some-action
        with:
          modules: ${{ steps.import_modules.outputs.modules }}