name: POC_package_versioning
on: 
    workflow_dispatch:
    push:
        branches: [ action-ci ]
        paths:
            - .github/workflows/package-versioning.yaml

jobs:
  package-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: json property
        id: json_properties
        run: |
          echo "RELEASE_TAG=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - run: |
          echo "Build tag==> ${{ steps.json_properties.outputs.RELEASE_TAG }}"

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy -y

      - name: Read JSON from file and run Groovy script
        run: |
          groovy -e '''
              def json = new File("package.json").text
              def parsedJson = new groovy.json.JsonSlurper().parseText(json)
              def packageVersionInJson =  parsedJson.version
              println "${packageVersionInJson}"
              println "Package Version (package.json): ${packageVersionInJson}"
          '''
          
      # - run: |
      #     groovy -e '''
      #       def packageJson = readJSON file: "package.json"
      #       def packageVersionInJson = packageJson.version
      #       println "Package Version (package.json): ${packageVersionInJson}"
      #     '''

