name: POC_read_json
on: 
  workflow_dispatch:
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/read-var-file.yaml
  
jobs:
  set-env-fromJson:
    runs-on: ubuntu-latest
    outputs: 
      AZ_CONTAINER_REGISTRY: ${{ fromJson(env.CONFIG_JSON).AZ_CONTAINER_REGISTRY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: |
            echo "CONFIG_JSON=$(jq -c . < config-var.json)" >> $GITHUB_ENV
      # - run: |
      #       env
      #       echo "fromJson: ${{ fromJson(env.CONFIG_JSON).AZ_CONTAINER_REGISTRY }}"
      #       echo "env: ${{env.CONFIG_JSON}}"

  # env_workflow:
  #   runs-on: ubuntu-latest
  #   name: Preparation Environment
  #   outputs: 
  #     AZ_CONTAINER_REGISTRY: ${{ fromJson(env.CONFIG_JSON).AZ_CONTAINER_REGISTRY }}
  #   steps:
  #     - run: |
  #         echo "preparing output env"

  json-from-vars:
    runs-on: ubuntu-latest
    needs: set-env-fromJson
    steps:
      - name: check variable from setting
        run : |
            echo "variable: ${{ fromJson(vars.JSON).AZ_CONTAINER_NAME }}"

  json-from-env-output:
    runs-on: ubuntu-latest
    needs: [set-env-fromJson]
    steps:
      - name: check variable from setting
        run : |
            echo "env output : ${{needs.env_workflow.outputs.AZ_CONTAINER_REGISTRY}}