name: POC_read_json
on: 
  workflow_dispatch:
  push:
    branches: [ action-ci ]
    paths:
      - .github/workflows/read-var-file.yaml

jobs:
  set-env-fromJson:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: |
            echo "CONFIG_JSON=$(jq -c . < config-var.json)" >> $GITHUB_ENV
      - run: |
            env
            echo "fromJson: ${{ fromJson(env.CONFIG_JSON).AZ_CONTAINER_REGISTRY }}"
            echo "env: ${{env.CONFIG_JSON}}"

  job-call:
    runs-on: ubuntu-latest
    needs: set-env-fromJson
    steps:
      - name: echo env from GITHUB_ENV
        run : |
            echo "variable: ${{ fromJson(env.JSON).AZ_CONTAINER_NAME }}"