name: POC_run-name
on:
  workflow_dispatch:
    inputs:
      Version:
        required: true
        type: string
        description: "Version x.x.x" 
      SourceCodeBranch:
        required: true
        default: main
        type: string
      choice:
        type: choice
        description: 'VersioningType'
        default: 'Release'
        options:
          - 'Release'
          - 'Snapshot'
  push:
run-name: ${{ github.workflow }} - ${{ format('{0} Branch={1}', tojson(inputs), github.ref_name) || '' }}
# run-name: ${{ github.event_name == 'workflow_dispatch' && format('Build Maven Libs with {0} On Branch {1}', toJson(inputs), github.ref_name) || '' }}

jobs:
  testa:
    runs-on: ubuntu-latest
    steps:
    - run: ${{tojson(inputs)}}
      shell: cat {0}
    - run: ${{tojson(github.event.inputs)}}
      shell: cat {0}