name: POC_run-name
on:
  workflow_dispatch:
    inputs:
      test:
        type: choice
        options:
        - mychoice
        - a
        - b
      b:
        type: boolean
  push:
run-name: ${{ github.event_name == 'workflow_dispatch' && format('CI/CD-{0}-branch-{1}', tojson(inputs), github.ref_name) || '' }}
jobs:
  testa:
    runs-on: ubuntu-latest
    steps:
    - run: ${{tojson(inputs)}}
      shell: cat {0}
    - run: ${{tojson(github.event.inputs)}}
      shell: cat {0}