name: POC-vault-create-update

on: 
  workflow_dispatch:
    inputs:
        VAULT_KEY: 
          type: string
          required: true
        VAULT_SECRET: 
          type: string
          required: true

env:
    vault_addr: http://4.194.34.125:8200
jobs:
    vault-preparation:
        runs-on: ubuntu-latest
        steps:
            - name: prepare data
              run: | 
                  export VAULT_ADDR=${vault_addr}
                  vault kv put secret/test ${{inputs.VAULT_KEY}}=${{inputs.VAULT_SECRET}}
                  vault kv get secret/test

