name: POC-vault-create-update

on: 
  workflow_dispatch:
    inputs:
        VAULT_KEY: 
          type: string
          required: true
        VAULT_SECRET: 
          type: string
          required: true

env:
    vault_addr: http://4.194.34.125:8200
    vault_token: ${{secrets.VAULT_TOKEN}}
    vaultSecretPath: secret/test
jobs:
    vault-import:
        runs-on: ubuntu-latest
        steps:
            - name: vaultcli-installation
              run: |
                sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt update
                sudo apt install vault -y
                sudo vault --version

            - name: prepare data
              run: | 
                  export VAULT_ADDR=${vault_addr}
                  export VAULT_TOKEN=${vault_token}

                  SECRET_PATH=$(vault kv get ${{env.vaultSecretPath}} 2>/dev/null)
                  if [ -z "${SECRET_PATH}" ];then
                      echo "Create new path"
                      vault kv put ${{env.vaultSecretPath}} ${{inputs.VAULT_KEY}}=${{inputs.VAULT_SECRET}}
                  else
                      echo "Update existing"
                      vault kv patch ${{env.vaultSecretPath}} ${{inputs.VAULT_KEY}}=${{inputs.VAULT_SECRET}}
                  fi

    reteive-vault-hashicorp-workflow:
        needs: vault-import
        runs-on: ubuntu-latest
        steps:
            - name: Import Secrets
              id: get-secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://4.194.34.125:8200
                token: ${{ secrets.VAULT_TOKEN }}
                tlsSkipVerify: true
                secrets: |
                    secret/data/test ${{inputs.VAULT_KEY}} | SECRET_ID

            - name: reteive the secret from vault
              run : |
                  echo "my user: ${{env.SECRET_ID}}"


