
name: POC_working_dir
on: 
    push:
        branches: [ action-ci ]
        paths:
        - .github/workflows/working-dir.yaml
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        path: source_code

    - name: Check out helmchart
      uses: actions/checkout@v3
      with:
        repository: brightza008/poc-helmchart
        ref: minikube
        path: helmchart

    - name: Check out helmvalue
      uses: actions/checkout@v3
      with:
        repository: MuZikZz-Org/Helm-Vaules
        ref: main
        path: helmvalue

    - run: |
        ls -R
        ls -lrt

    - name: Save workspace
      run: |
        touch workspace.tar.gz
        tar --exclude=workspace.tar.gz -czf workspace.tar.gz .
      continue-on-error: true

    - name: Upload workspace artifact
      uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: workspace.tar.gz

  Call_reused_working_dir: 
    needs: [Checkout]
    name: "Compress file(zip,tar) and Upload to StorageAccount"
    uses: brightza008/poc-github-workflow/.github/workflows/reused-working-dir.yaml@workflow
    with:
      workspace: "shared_working_dir"